-- ============================================================================
-- Script SQL para generar 365 días de datos históricos REALISTAS de consumo
-- ============================================================================
-- Este script genera datos de consumo diario para los últimos 365 días
-- con variaciones realistas por día de semana, estacionalidad y tipo de producto
--
-- CARACTERÍSTICAS:
-- - Genera datos para los últimos 365 días
-- - Variación por día de semana (lunes-viernes más consumo)
-- - Variación estacional (invierno más consumo de ciertos productos)
-- - Distribución realista por áreas
-- - Diferentes tasas de consumo según tipo de producto
-- - Idempotente: puede ejecutarse múltiples veces sin duplicar datos
--
-- USO:
-- 1. Abrir MySQL Workbench
-- 2. Conectarse a la base de datos rfid_stock_db
-- 3. Ejecutar este script completo (Ctrl+Shift+Enter)
-- 4. Esperar 2-5 minutos dependiendo del número de productos
-- ============================================================================

-- Configurar fechas
SET @start_date = DATE_SUB(CURDATE(), INTERVAL 365 DAY);
SET @end_date = CURDATE();

-- Limpiar datos históricos generados anteriormente (OPCIONAL - descomentar si quieres regenerar)
-- DELETE FROM stock_history WHERE consumption_date >= @start_date AND notes LIKE 'Generated by 365_days_history script%';

-- ============================================================================
-- TABLA TEMPORAL: Generar secuencia de fechas (365 días)
-- ============================================================================

DROP TEMPORARY TABLE IF EXISTS temp_dates;
CREATE TEMPORARY TABLE temp_dates (
    date_val DATE PRIMARY KEY,
    day_of_week INT,
    month_num INT,
    day_multiplier DECIMAL(4,2),
    season_multiplier DECIMAL(4,2)
);

INSERT INTO temp_dates (date_val, day_of_week, month_num, day_multiplier, season_multiplier)
SELECT 
    DATE_ADD(@start_date, INTERVAL seq.seq DAY) as date_val,
    DAYOFWEEK(DATE_ADD(@start_date, INTERVAL seq.seq DAY)) - 1 as day_of_week,
    MONTH(DATE_ADD(@start_date, INTERVAL seq.seq DAY)) as month_num,
    CASE DAYOFWEEK(DATE_ADD(@start_date, INTERVAL seq.seq DAY))
        WHEN 1 THEN 0.6  -- Domingo
        WHEN 2 THEN 0.8  -- Lunes
        WHEN 3 THEN 1.0  -- Martes
        WHEN 4 THEN 1.0  -- Miércoles
        WHEN 5 THEN 1.0  -- Jueves
        WHEN 6 THEN 1.2  -- Viernes
        ELSE 0.7         -- Sábado
    END as day_multiplier,
    CASE 
        WHEN MONTH(DATE_ADD(@start_date, INTERVAL seq.seq DAY)) IN (12,1,2) THEN 1.15  -- Invierno
        WHEN MONTH(DATE_ADD(@start_date, INTERVAL seq.seq DAY)) IN (6,7,8) THEN 0.9    -- Verano
        ELSE 1.0
    END as season_multiplier
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 as seq
    FROM (SELECT 0 as N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a
    CROSS JOIN (SELECT 0 as N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b
    CROSS JOIN (SELECT 0 as N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4) c
) seq
WHERE DATE_ADD(@start_date, INTERVAL seq.seq DAY) < @end_date;

-- ============================================================================
-- GENERAR CONSUMO PARA MEDICAMENTOS
-- ============================================================================

INSERT INTO stock_history (
    product_id, batch_id, area_id, previous_stock, new_stock, action, consumption_date, notes, created_at
)
SELECT 
    p.id as product_id,
    (SELECT pb.id 
     FROM product_batches pb 
     WHERE pb.product_id = p.id 
       AND pb.quantity > 0 
       AND pb.expiry_date >= CURDATE()
     ORDER BY pb.expiry_date ASC, pb.entry_date ASC 
     LIMIT 1) as batch_id,
    (SELECT a.id 
     FROM areas a 
     WHERE a.is_active = 1 
     ORDER BY RAND() 
     LIMIT 1) as area_id,
    COALESCE((
        SELECT SUM(pb2.quantity) 
        FROM product_batches pb2 
        WHERE pb2.product_id = p.id
    ), 0) as previous_stock,
    GREATEST(0, COALESCE((
        SELECT SUM(pb2.quantity) 
        FROM product_batches pb2 
        WHERE pb2.product_id = p.id
    ), 0) - FLOOR(15 * d.day_multiplier * d.season_multiplier * (0.85 + RAND() * 0.3))) as new_stock,
    'remove' as action,
    d.date_val as consumption_date,
    'Generated by 365_days_history script - medicamento' as notes,
    CONCAT(d.date_val, ' ', TIME(NOW())) as created_at
FROM products p
CROSS JOIN temp_dates d
WHERE p.product_type = 'medicamento'
  AND EXISTS (
      SELECT 1 
      FROM product_batches pb 
      WHERE pb.product_id = p.id 
        AND pb.quantity > 0
  )
  AND NOT EXISTS (
      SELECT 1 
      FROM stock_history sh
      WHERE sh.product_id = p.id
        AND sh.consumption_date = d.date_val
        AND sh.action = 'remove'
        AND sh.notes LIKE 'Generated by 365_days_history script%'
  )
  AND COALESCE((
      SELECT SUM(pb2.quantity) 
      FROM product_batches pb2 
      WHERE pb2.product_id = p.id
  ), 0) > 0;

-- ============================================================================
-- GENERAR CONSUMO PARA INSUMOS
-- ============================================================================

INSERT INTO stock_history (
    product_id, batch_id, area_id, previous_stock, new_stock, action, consumption_date, notes, created_at
)
SELECT 
    p.id as product_id,
    (SELECT pb.id 
     FROM product_batches pb 
     WHERE pb.product_id = p.id 
       AND pb.quantity > 0 
       AND pb.expiry_date >= CURDATE()
     ORDER BY pb.expiry_date ASC, pb.entry_date ASC 
     LIMIT 1) as batch_id,
    (SELECT a.id 
     FROM areas a 
     WHERE a.is_active = 1 
     ORDER BY RAND() 
     LIMIT 1) as area_id,
    COALESCE((
        SELECT SUM(pb2.quantity) 
        FROM product_batches pb2 
        WHERE pb2.product_id = p.id
    ), 0) as previous_stock,
    GREATEST(0, COALESCE((
        SELECT SUM(pb2.quantity) 
        FROM product_batches pb2 
        WHERE pb2.product_id = p.id
    ), 0) - FLOOR(25 * d.day_multiplier * d.season_multiplier * (0.85 + RAND() * 0.3))) as new_stock,
    'remove' as action,
    d.date_val as consumption_date,
    'Generated by 365_days_history script - insumo' as notes,
    CONCAT(d.date_val, ' ', TIME(NOW())) as created_at
FROM products p
CROSS JOIN temp_dates d
WHERE p.product_type = 'insumo'
  AND EXISTS (
      SELECT 1 
      FROM product_batches pb 
      WHERE pb.product_id = p.id 
        AND pb.quantity > 0
  )
  AND NOT EXISTS (
      SELECT 1 
      FROM stock_history sh
      WHERE sh.product_id = p.id
        AND sh.consumption_date = d.date_val
        AND sh.action = 'remove'
        AND sh.notes LIKE 'Generated by 365_days_history script%'
  )
  AND COALESCE((
      SELECT SUM(pb2.quantity) 
      FROM product_batches pb2 
      WHERE pb2.product_id = p.id
  ), 0) > 0;

-- ============================================================================
-- GENERAR CONSUMO PARA DISPOSITIVOS
-- ============================================================================

INSERT INTO stock_history (
    product_id, batch_id, area_id, previous_stock, new_stock, action, consumption_date, notes, created_at
)
SELECT 
    p.id as product_id,
    (SELECT pb.id 
     FROM product_batches pb 
     WHERE pb.product_id = p.id 
       AND pb.quantity > 0 
       AND pb.expiry_date >= CURDATE()
     ORDER BY pb.expiry_date ASC, pb.entry_date ASC 
     LIMIT 1) as batch_id,
    (SELECT a.id 
     FROM areas a 
     WHERE a.is_active = 1 
     ORDER BY RAND() 
     LIMIT 1) as area_id,
    COALESCE((
        SELECT SUM(pb2.quantity) 
        FROM product_batches pb2 
        WHERE pb2.product_id = p.id
    ), 0) as previous_stock,
    GREATEST(0, COALESCE((
        SELECT SUM(pb2.quantity) 
        FROM product_batches pb2 
        WHERE pb2.product_id = p.id
    ), 0) - FLOOR(3 * d.day_multiplier * d.season_multiplier * (0.85 + RAND() * 0.3))) as new_stock,
    'remove' as action,
    d.date_val as consumption_date,
    'Generated by 365_days_history script - dispositivo' as notes,
    CONCAT(d.date_val, ' ', TIME(NOW())) as created_at
FROM products p
CROSS JOIN temp_dates d
WHERE p.product_type = 'dispositivo'
  AND EXISTS (
      SELECT 1 
      FROM product_batches pb 
      WHERE pb.product_id = p.id 
        AND pb.quantity > 0
  )
  AND NOT EXISTS (
      SELECT 1 
      FROM stock_history sh
      WHERE sh.product_id = p.id
        AND sh.consumption_date = d.date_val
        AND sh.action = 'remove'
        AND sh.notes LIKE 'Generated by 365_days_history script%'
  )
  AND COALESCE((
      SELECT SUM(pb2.quantity) 
      FROM product_batches pb2 
      WHERE pb2.product_id = p.id
  ), 0) > 0;

-- ============================================================================
-- GENERAR CONSUMO PARA VACUNAS
-- ============================================================================

INSERT INTO stock_history (
    product_id, batch_id, area_id, previous_stock, new_stock, action, consumption_date, notes, created_at
)
SELECT 
    p.id as product_id,
    (SELECT pb.id 
     FROM product_batches pb 
     WHERE pb.product_id = p.id 
       AND pb.quantity > 0 
       AND pb.expiry_date >= CURDATE()
     ORDER BY pb.expiry_date ASC, pb.entry_date ASC 
     LIMIT 1) as batch_id,
    (SELECT a.id 
     FROM areas a 
     WHERE a.is_active = 1 
     ORDER BY RAND() 
     LIMIT 1) as area_id,
    COALESCE((
        SELECT SUM(pb2.quantity) 
        FROM product_batches pb2 
        WHERE pb2.product_id = p.id
    ), 0) as previous_stock,
    GREATEST(0, COALESCE((
        SELECT SUM(pb2.quantity) 
        FROM product_batches pb2 
        WHERE pb2.product_id = p.id
    ), 0) - FLOOR(8 * d.day_multiplier * d.season_multiplier * (0.85 + RAND() * 0.3))) as new_stock,
    'remove' as action,
    d.date_val as consumption_date,
    'Generated by 365_days_history script - vacuna' as notes,
    CONCAT(d.date_val, ' ', TIME(NOW())) as created_at
FROM products p
CROSS JOIN temp_dates d
WHERE p.product_type = 'vacuna'
  AND EXISTS (
      SELECT 1 
      FROM product_batches pb 
      WHERE pb.product_id = p.id 
        AND pb.quantity > 0
  )
  AND NOT EXISTS (
      SELECT 1 
      FROM stock_history sh
      WHERE sh.product_id = p.id
        AND sh.consumption_date = d.date_val
        AND sh.action = 'remove'
        AND sh.notes LIKE 'Generated by 365_days_history script%'
  )
  AND COALESCE((
      SELECT SUM(pb2.quantity) 
      FROM product_batches pb2 
      WHERE pb2.product_id = p.id
  ), 0) > 0;

-- ============================================================================
-- LIMPIAR TABLA TEMPORAL
-- ============================================================================

DROP TEMPORARY TABLE IF EXISTS temp_dates;

-- ============================================================================
-- RESUMEN FINAL
-- ============================================================================

SELECT 
    'Datos históricos generados exitosamente' as mensaje,
    COUNT(*) as total_registros,
    MIN(consumption_date) as fecha_inicio,
    MAX(consumption_date) as fecha_fin
FROM stock_history
WHERE notes LIKE 'Generated by 365_days_history script%';

SELECT 
    p.product_type,
    COUNT(DISTINCT sh.product_id) as productos_con_historial,
    COUNT(*) as total_registros
FROM stock_history sh
JOIN products p ON sh.product_id = p.id
WHERE sh.notes LIKE 'Generated by 365_days_history script%'
GROUP BY p.product_type;
